### ISSUE TITLE
As a data user, I want to view ODR S3 bucket with S3 browser app

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/s3-browser-cloudfront#22]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Data engineer

### 💪 Motivation

...so that I can expose my bucket to my user who would like to browse and download the datasets.

### Acceptance Criteria

**Given** ODR s3 bucket (for example https://aws.amazon.com/marketplace/pp/prodview-zetjfybagtrl2?sr=0-8&ref_=beagle&applicationId=AWSMPContessa#resources)
**When I perform** a deployment of s3-browser with proper configuration
**Then I expect** to have web pages enabling users to browse the file or the bucket and download them through an HTTP link to S3 without going through cloudfront or any proxy server.

**Comment by tloubrieu-jpl** [comment]
@eddiesarevalo uses the USGS code and is able to show the ODR bucket and another S3 bucket.

The style remains to be worked on, so to add what we had in the previous demo.

And there are CORS issues to resolve.

**Comment by eddiesarevalo** [comment]
https://github.com/NASA-PDS/s3-browser-cloudfront/commit/09abccd28ce411289988e8b6667a8cbf0f184178

**Comment by tloubrieu-jpl** [comment]
The style is back, we will discuss the CORS issues during the breakout.

**Comment by tloubrieu-jpl** [comment]
The bucket got allow only SSL which made the portal get 403 errors. @eddiesarevalo removed it so that it works again.

**Comment by jordanpadams** [comment]
status: SSL policy on bucket was tested successfully. 🎉 

fixed minor bug with slashes

**Comment by jordanpadams** [comment]
- [ ] @viviant100 to SSL policy from pds-infra-temp to ODR bucket and confirm with Eddie to test

**Comment by jordanpadams** [comment]
@eddiesarevalo do we have a PR for this and #25 ready?

**Comment by viviant100** [comment]
> * [ ]  @viviant100 to SSL policy from pds-infra-temp to ODR bucket and confirm with Eddie to test

Done.

**Comment by jordanpadams** [comment]
resolved by https://github.com/NASA-PDS/s3-browser-cloudfront/pull/30

**Comment by jordanpadams** [comment]
and task above by @viviant100

**Comment by jordanpadams** [comment]
Skipping I&T. Tested via inspection during website deployment
