### ISSUE TITLE
Test out s3-browser with buckets that require HTTPS connections only

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/s3-browser-cloudfront#25]
### 💡 Description

We need to restrict access to the ODR buckets to require HTTPS connections only. Let's test out s3-browser-cloudfront with that configuration.

**Comment by jordanpadams** [comment]
See https://github.com/NASA-PDS/s3-browser-cloudfront/issues/22#issuecomment-2059862157 for final step for copying the SSL policy over to ODR

**Comment by tloubrieu-jpl** [comment]
@viviant100 will update the policy later.

**Comment by viviant100** [comment]
SSL policy is now added to ODR bucket policy and verified that we can run the file viewer app and view the CSS contents.
