### ISSUE TITLE
Deploy S3 Browser to Test and Prod

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/s3-browser-cloudfront#29]
### 💡 Description

Once we have this tested out, we should deploy to test and production

**Comment by jordanpadams** [comment]
@viviant100 @tloubrieu-jpl FYI, here is that ticket for deploying this to test/production.

**Comment by jordanpadams** [comment]
@viviant100 @tloubrieu-jpl note: I added this to the sprint since I believe it comes mostly for free when we get the API deployed, but we can move from the backlog if we do not think that is possible.

**Comment by viviant100** [comment]
This has been deployed to MCP test environment

**Comment by tloubrieu-jpl** [comment]
This is deployed in test and production, see https://pds.mcp.nasa.gov/data/
