### ISSUE TITLE
Use bucket `pds-logs-dev` instead of  `pds-s3-browser-logs` for logs in DEv on MCP

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/s3-browser-cloudfront#67]
### 💡 Description

Do what is in the title and then delete the bucket `pds-s3-browser-logs`

**Comment by tloubrieu-jpl** [comment]
@viviant100 I created this ticket for Eddie to switch the s3 bcuket for logs in Dev.

**Comment by eddiesarevalo** [comment]
All dev cloudfronts now point to pds-logs-dev bucket.

**Comment by tloubrieu-jpl** [comment]
Thanks @eddiesarevalo , I deleted the bucket `pds-s3-browser-logs`.
