### ISSUE TITLE
Upgrade ws, braces, DOMPurify, body-parser dependencies

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/s3-browser-cloudfront#94]
### 💡 Description

- https://github.com/NASA-PDS/s3-browser-cloudfront/security/dependabot/11
- https://github.com/NASA-PDS/s3-browser-cloudfront/security/dependabot/7
- https://github.com/NASA-PDS/s3-browser-cloudfront/security/dependabot/16
- https://github.com/NASA-PDS/s3-browser-cloudfront/security/dependabot/12

**Comment by eddiesarevalo** [comment]
@jordanpadams Tested and approved: https://github.com/NASA-PDS/s3-browser-cloudfront/pull/98#pullrequestreview-2326527373

**Comment by jordanpadams** [comment]
All upgraded successfully
